edition = "2021"
newline_style = "Unix"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
force_multiline_blocks = true

reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Off"

indent_style = "Block"
match_arm_blocks = true